//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace nicorank.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nicorank.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   version	2
        ///all	all	総合	10	10	10	3	1
        ///ent	ent	エンターテイメント	3	1	1	1	0
        ///music	mus	音楽	3	1	1	1	0
        ///sport	spt	スポーツ	3	1	1	1	0
        ///animal	anl	動物	3	1	1	1	0
        ///cooking	cok	料理	3	1	1	1	0
        ///diary	dia	日記	3	1	1	1	0
        ///nature	nat	自然	3	1	1	1	0
        ///science	sci	科学	3	1	1	1	0
        ///history	his	歴史	3	1	1	1	0
        ///radio	rad	ラジオ	3	1	1	1	0
        ///lecture	lec	ニコニコ動画講座	3	1	1	1	0
        ///politics	pol	政治	3	1	1	1	0
        ///sing	sng	歌ってみた	3	1	1	1	0
        ///play	ply	演奏してみた	3	1	1	1	0
        ///dance	dnc	踊ってみた	3	1	1	1	0
        ///draw	drw	描いてみた	3	1	1	1	0
        ///tech	tec	ニコニコ技術部	3	1	1	1	0
        ///anime	ame	アニメ	3	1	1	1	0
        ///ga [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   all	all	総合	10	10	10	3	1
        ///ent	ent	エンターテイメント	3	1	1	1	0
        ///music	mus	音楽	3	1	1	1	0
        ///sport	spt	スポーツ	3	1	1	1	0
        ///animal	anl	動物	3	1	1	1	0
        ///fashion	fas	ファッション	3	1	1	1	0
        ///cooking	cok	料理	3	1	1	1	0
        ///diary	dia	日記	3	1	1	1	0
        ///nature	nat	自然	3	1	1	1	0
        ///science	sci	科学	3	1	1	1	0
        ///history	his	歴史	3	1	1	1	0
        ///radio	rad	ラジオ	3	1	1	1	0
        ///lecture	lec	ニコニコ動画講座	3	1	1	1	0
        ///politics	pol	政治	3	1	1	1	0
        ///sing	sng	歌ってみた	3	1	1	1	0
        ///play	ply	演奏してみた	3	1	1	1	0
        ///dance	dnc	踊ってみた	3	1	1	1	0
        ///draw	drw	描いてみた	3	1	1	1	0
        ///tech	tec	ニコニコ技術部	3	1	1	1	0
        ///anime	am [残りの文字列は切り詰められました]&quot;; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string category204 {
            get {
                return ResourceManager.GetString("category204", resourceCulture);
            }
        }
    }
}
