//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace nicorank.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("nicorank.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to version	2
        ///all	all	総合	10	10	10	3	1
        ///ent	ent	エンターテイメント	3	1	1	1	0
        ///music	mus	音楽	3	1	1	1	0
        ///sport	spt	スポーツ	3	1	1	1	0
        ///animal	anl	動物	3	1	1	1	0
        ///cooking	cok	料理	3	1	1	1	0
        ///diary	dia	日記	3	1	1	1	0
        ///nature	nat	自然	3	1	1	1	0
        ///science	sci	科学	3	1	1	1	0
        ///history	his	歴史	3	1	1	1	0
        ///radio	rad	ラジオ	3	1	1	1	0
        ///lecture	lec	ニコニコ動画講座	3	1	1	1	0
        ///politics	pol	政治	3	1	1	1	0
        ///sing	sng	歌ってみた	3	1	1	1	0
        ///play	ply	演奏してみた	3	1	1	1	0
        ///dance	dnc	踊ってみた	3	1	1	1	0
        ///draw	drw	描いてみた	3	1	1	1	0
        ///tech	tec	ニコニコ技術部	3	1	1	1	0
        ///anime	ame	アニメ	3	1	1	1	0
        ///ga [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string category {
            get {
                return ResourceManager.GetString("category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all	all	総合	10	10	10	3	1
        ///ent	ent	エンターテイメント	3	1	1	1	0
        ///music	mus	音楽	3	1	1	1	0
        ///sport	spt	スポーツ	3	1	1	1	0
        ///animal	anl	動物	3	1	1	1	0
        ///fashion	fas	ファッション	3	1	1	1	0
        ///cooking	cok	料理	3	1	1	1	0
        ///diary	dia	日記	3	1	1	1	0
        ///nature	nat	自然	3	1	1	1	0
        ///science	sci	科学	3	1	1	1	0
        ///history	his	歴史	3	1	1	1	0
        ///radio	rad	ラジオ	3	1	1	1	0
        ///lecture	lec	ニコニコ動画講座	3	1	1	1	0
        ///politics	pol	政治	3	1	1	1	0
        ///sing	sng	歌ってみた	3	1	1	1	0
        ///play	ply	演奏してみた	3	1	1	1	0
        ///dance	dnc	踊ってみた	3	1	1	1	0
        ///draw	drw	描いてみた	3	1	1	1	0
        ///tech	tec	ニコニコ技術部	3	1	1	1	0
        ///anime	am [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string category204 {
            get {
                return ResourceManager.GetString("category204", resourceCulture);
            }
        }
    }
}
